# Generated by Django 5.2.6 on 2025-09-23 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0003_dicominstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Tên định danh cho mô hình', max_length=255, unique=True)),
                ('model_version', models.CharField(help_text='Phiên bản hiện tại của mô hình', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về mô hình')),
                ('model_path', models.CharField(help_text='Đường dẫn tương đối đến file trọng số', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_result', models.JSONField(help_text='Kết quả dự đoán chi tiết dưới dạng JSON')),
                ('heatmap_image_path', models.CharField(help_text='Đường dẫn tới heatmap đã tạo', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='ai_processing.aimodel')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='uploads.dicomstudy')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('review_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_status', models.CharField(choices=[('CORRECT', 'Chính xác'), ('INCORRECT', 'Không chính xác'), ('IRRELEVANT', 'Không liên quan')], help_text='Đánh giá của chuyên gia', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True, help_text='Nhận xét chi tiết')),
                ('annotated_regions', models.JSONField(blank=True, help_text='Vùng quan trọng được chuyên gia đánh dấu', null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ai_processing.aireport')),
                ('user', models.ForeignKey(help_text='Chuyên gia thực hiện đánh giá', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
