# Generated by Django 5.2.6 on 2025-10-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0002_imageadjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageadjustments',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Liên kết đến báo cáo AI sau khi dự đoán', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='ai_processing.aireport'),
        ),
    ]
