# Generated by Django 5.2.6 on 2025-10-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0003_imageadjustments_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadjustments',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Báo cáo AI liên kết với các chỉnh sửa này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='ai_processing.aireport'),
        ),
    ]
