# Generated by Django 5.2.6 on 2025-10-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0004_alter_imageadjustments_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='heatmap_image_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='prediction_result',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='imageadjustments',
            name='adjustment_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='imageadjustments',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='ai_processing.aireport'),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='annotated_regions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='reviewer_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='reviewer_status',
            field=models.CharField(choices=[('CORRECT', 'Chính xác'), ('INCORRECT', 'Không chính xác'), ('IRRELEVANT', 'Không liên quan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
