# Generated by Django 5.2.6 on 2025-10-06 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0005_alter_aimodel_description_alter_aimodel_model_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả chi tiết về mô hình'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_name',
            field=models.CharField(help_text='Tên định danh cho mô hình', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_path',
            field=models.CharField(help_text='Đường dẫn tương đối đến file trọng số', max_length=1024),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_version',
            field=models.CharField(help_text='Phiên bản hiện tại của mô hình', max_length=50),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='heatmap_image_path',
            field=models.CharField(help_text='Đường dẫn tới heatmap đã tạo', max_length=1024),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='prediction_result',
            field=models.JSONField(help_text='Kết quả dự đoán chi tiết dưới dạng JSON'),
        ),
        migrations.AlterField(
            model_name='imageadjustments',
            name='adjustment_json',
            field=models.JSONField(help_text='Thông số chỉnh sửa (zoom, contrast, brightness, filter, vv)'),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='annotated_regions',
            field=models.JSONField(blank=True, help_text='Vùng quan trọng được chuyên gia đánh dấu', null=True),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='reviewer_comments',
            field=models.TextField(blank=True, help_text='Nhận xét chi tiết'),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='reviewer_status',
            field=models.CharField(choices=[('CORRECT', 'Chính xác'), ('INCORRECT', 'Không chính xác'), ('IRRELEVANT', 'Không liên quan')], help_text='Đánh giá của chuyên gia', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='user',
            field=models.ForeignKey(help_text='Chuyên gia thực hiện đánh giá', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
