# Generated by Django 5.2.6 on 2025-10-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0006_alter_aimodel_description_alter_aimodel_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageadjustments',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reviewsession',
            name='annotated_regions',
        ),
    ]
