# Generated by Django 5.2.6 on 2025-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0007_remove_imageadjustments_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='annotated_regions',
            field=models.JSONField(blank=True, help_text='Vùng quan trọng được chuyên gia đánh dấu', null=True),
        ),
        migrations.DeleteModel(
            name='ImageAdjustments',
        ),
    ]
