# Generated by Django 5.2.6 on 2025-09-09 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID duy nhất cho mỗi bệnh nhân', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Họ và tên bệnh nhân', max_length=255)),
                ('date_of_birth', models.DateField(help_text='Ngày sinh của bệnh nhân')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Quản lý Bệnh nhân',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='Tên file gốc', max_length=255)),
                ('file_format', models.CharField(help_text='Định dạng file gốc (ví dụ: jpg, png, dcm)', max_length=50)),
                ('file', models.FileField(help_text='Đường dẫn tới file đã tải lên', upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(help_text='Người dùng đã tải file lên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='File này thuộc về bệnh nhân nào', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploads.patient')),
            ],
            options={
                'verbose_name': 'Tệp tải lên',
                'verbose_name_plural': 'Quản lý Tệp tải lên',
            },
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('study_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_description', models.TextField(blank=True, help_text='Mô tả về ca chụp/nghiên cứu')),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField()),
                ('orthanc_study_id', models.CharField(help_text='ID của Study trên server Orthanc', max_length=255, unique=True)),
                ('user', models.ForeignKey(help_text='Người dùng thực hiện ca chụp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Nghiên cứu này của bệnh nhân nào', on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='uploads.patient')),
            ],
            options={
                'verbose_name': 'Nghiên cứu DICOM',
                'verbose_name_plural': 'Quản lý Nghiên cứu DICOM',
            },
        ),
    ]
