# Generated by Django 5.2.6 on 2025-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='session_id',
            field=models.UUIDField(help_text='ID của phiên upload để theo dõi', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='study_instance_uid',
            field=models.CharField(help_text='Study Instance UID của ca chụp (dùng cho OHIF)', max_length=255, null=True, unique=True),
        ),
    ]
