# Generated by Django 5.2.6 on 2025-09-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_fileupload_file_dicomstudy_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('instance_uid', models.CharField(help_text='SOP Instance UID (0008,0018) duy nhất của ảnh', max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(help_text='Ảnh này thuộc về ca chụp nào', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='uploads.dicomstudy')),
            ],
        ),
    ]
